# Generated by Django 5.2.8 on 2025-12-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
