# Generated by Django 5.2.8 on 2025-12-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_playerdata_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
